const books = [
  {
    id: 0,
    title: "خوف 1",
    price: 1000,
    pages: 300,
    author: "أحمد خالد توفيق",
    language: "Arabic",
    category: "Horror",
    dscrp: "lorem",

    dscrp: "lorem",
  },
  {
    id: 1,
    title: "خوف 2",
    price: 1000,
    pages: 300,
    author: "أحمد خالد توفيق",
    language: "Arabic",
    category: "Horror",
    dscrp: "lorem",
  },
  {
    id: 2,
    title: "خوف 3",
    price: 1000,
    pages: 300,
    author: "أحمد خالد توفيق",
    language: "Arabic",
    category: "Horror",
    dscrp: "lorem",
  },
  {
    id: 3,
    title: "أرض زيكولا",
    price: 900,
    pages: 400,
    author: "أحمد خالد توفيق",
    language: "Arabic",
    category: "Fantasy",
    dscrp: "lorem",
  },
  {
    id: 4,
    title: "أماريتا",
    price: 1000,
    pages: 350,
    author: "أحمد خالد توفيق",
    language: "Arabic",
    category: "Fantasy",
    dscrp: "lorem",
  },
  {
    id: 5,
    title: "واد الذئاب المنسية",
    price: 1000,
    pages: 350,
    author: "أحمد خالد توفيق",
    language: "Arabic",
    category: "Fantasy",
    dscrp: "lorem",
  },
  {
    id: 6,
    title: "الأب الغني والأب الفقير",
    price: 900,
    pages: 500,
    author: "إيريك سيجال",
    language: "English",
    category: "Finance",
    dscrp: "lorem",
  },
  {
    id: 7,
    title: "اكستاسي",
    price: 4500,
    pages: 500,
    author: "إيريك سيجال",
    language: "English",
    category: "Science Fiction",
    dscrp: "lorem",
  },
  {
    id: 8,
    title: "أبابيل",
    price: 1300,
    pages: 300,
    author: "أحمد خالد توفيق",
    language: "Arabic",
    category: "Mystery",
    dscrp: "lorem",
  },
  {
    id: 9,
    title: "جومانا",
    price: 1200,
    pages: 250,
    author: "إيلين هورنبي",
    language: "English",
    category: "Romance",
    dscrp: "lorem",
  },
  {
    id: 10,
    title: "الجساسة",
    price: 1200,
    pages: 300,
    author: "أحمد خالد توفيق",
    language: "Arabic",
    category: "Mystery",
    dscrp: "lorem",
  },
  {
    id: 11,
    title: "عشها بسعادة",
    price: 1000,
    pages: 200,
    author: "علاء الدين أبو زيد",
    language: "Arabic",
    category: "Self-Help",
    dscrp: "lorem",
  },
  {
    id: 12,
    title: "كن الشخص الذي يجعلك سعيدا",
    price: 1200,
    pages: 250,
    author: "عُمر المُختار المَنصوري",
    language: "Arabic",
    category: "Self-Help",
    dscrp: "lorem",
  },
  {
    id: 13,
    title: "كن أقوى من مشاعرك",
    price: 1300,
    pages: 300,
    author: "أحمد خالد توفيق",
    language: "Arabic",
    category: "Self-Help",
    dscrp: "lorem",
  },
  {
    id: 14,
    title: "تحكم في أصوات عقلك",
    price: 1300,
    pages: 300,
    author: "جون أكاف",
    language: "English",
    category: "Psychology",
    dscrp: "lorem",
  },
  {
    id: 15,
    title: "أول 20 ساعة",
    price: 1200,
    pages: 200,
    author: "ستيفن كوفي",
    language: "Arabic",
    category: "Self-Help",
    dscrp: "lorem",
  },
  {
    id: 16,
    title: "قوة التفكير الإيجابي",
    price: 1400,
    pages: 300,
    author: "نابليون هيل",
    language: "English",
    category: "Personal Development",
    dscrp: "lorem",
  },
  {
    id: 17,
    title: "أغنى رجل في بابل",
    price: 750,
    pages: 200,
    author: "جورج سميلسر",
    language: "English",
    category: "Finance",
    dscrp: "lorem",
  },
  {
    id: 18,
    title: "العادات الذرية",
    price: 1000,
    pages: 400,
    author: "تشالز دويج",
    language: "English",
    category: "Personal  Development",
    dscrp: "lorem",
  },
  {
    id: 19,
    title: "قوة عقلك الباطن",
    price: 1000,
    pages: 200,
    author: "جوزيف ميرفي",
    language: "English",
    category: "Psychology",
    dscrp: "lorem",
  },
  {
    id: 20,
    title: "فن قراءة العقول",
    price: 1400,
    pages: 300,
    author: "روبرت غرين",
    language: "English",
    category: "Psychology",
    dscrp: "lorem",
  },
  {
    id: 21,
    title: "معجزة الصباح",
    price: 900,
    pages: 200,
    author: "هال إلرود",
    language: "English",
    category: "Self-Help",
    dscrp: "lorem",
  },
  {
    id: 22,
    title: "فكر كأنك طبيب نفسي",
    price: 1300,
    pages: 400,
    author: "ألبرت إليس",
    language: "English",
    category: "Psychology",
    dscrp: "lorem",
  },
  {
    id: 23,
    title: "جلسات نفسية",
    price: 1000,
    pages: 300,
    author: "د. أحمد عبد الله سعفان",
    language: "Arabic",
    category: "Psychology",
    dscrp: "lorem",
  },
  {
    id: 24,
    title: "فن الإغواء",
    price: 3000,
    pages: 300,
    author: "روبرت غرين",
    language: "English",
    category: "Psychology",
    dscrp: "lorem",
  },
  {
    id: 25,
    title: "ڤيتامينات نفسية",
    price: 850,
    pages: 200,
    author: "علاء الدين أبو زيد",
    language: "Arabic",
    category: "Psychology",
    dscrp: "lorem",
  },
  {
    id: 26,
    title: "أبي الذي أكره",
    price: 1000,
    pages: 200,
    author: "أحمد خالد توفيق",
    language: "Arabic",
    category: "Mystery",
    dscrp: "lorem",
  },
  {
    id: 27,
    title: "كن أقوى من مشاعرك",
    price: 1300,
    pages: 300,
    author: "أحمد خالد توفيق",
    language: "Arabic",
    category: "Self-Help",
    dscrp: "lorem",
  },
  {
    id: 28,
    title: "قهوة صباحية مع النفس",
    price: 1500,
    pages: 200,
    author: "د. أحمد عبد الله سعفان",
    language: "Arabic",
    category: "Self-Help",
    dscrp: "lorem",
  },
  {
    id: 29,
    title: "الوحش الذي يسكنك يمكن أن يكون لطيفا",
    price: 1300,
    pages: 300,
    author: "د. أحمد عبد الله سعفان",
    language: "Arabic",
    category: "Psychology",
    dscrp: "lorem",
  },
];

export default books;
